id: I66E33C67
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T00:03:22+00:00'
last_modified: '2022-06-09T04:29:49.385964+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD133159
  title: གཞོན་ནུ་དྲུག་གི་རྟོགས་བརྗོད། ༼དབྱིན་བོད་ཤན་སྦྱར།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D809:
      image_group_id: I2PD19047
      title: Volume 1 of gzhon nu drug gi rtogs brjod/ (dbyin bod shan sbyar/)
      total_pages: 262
      order: 1
      base_file: D809.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
