id: opecha:P008100
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD133159
  title: གཞོན་ནུ་དྲུག་གི་རྟོགས་བརྗོད། ༼དབྱིན་བོད་ཤན་སྦྱར།༽
  volume:
    01d50930002248e09fb0c16c8c8de34b:
      image_group_id: I2PD19047
      title: Volume 1 of gzhon nu drug gi rtogs brjod/ (dbyin bod shan sbyar/)
      volume_number: 1
      total_pages: 262
  author: ''
ebook_metadata:
  title: གཞོན་ནུ་དྲུག་གི་རྟོགས་བརྗོད། ༼དབྱིན་བོད་ཤན་སྦྱར།༽
  author: ''
  sku: P008100
  cover: cover.jpg
  layers:
  - pagination
