id: P008100
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD133159
  title: གཞོན་ནུ་དྲུག་གི་རྟོགས་བརྗོད། ༼དབྱིན་བོད་ཤན་སྦྱར།༽
  author: ''
  volumes:
    d8d177669c90403bbce38567691b7614:
      image_group_id: I2PD19047
      title: ''
      volume_number: 1
      total_pages: 262
ebook_metadata:
  title: གཞོན་ནུ་དྲུག་གི་རྟོགས་བརྗོད། ༼དབྱིན་བོད་ཤན་སྦྱར།༽
  author: ''
  sku: P008100
  cover: cover.jpg
  layers:
  - pagination
