id: P008100
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 13:01:32.811760
source_metadata:
  id: bdr:W1PD133159
  title: གཞོན་ནུ་དྲུག་གི་རྟོགས་བརྗོད། ༼དབྱིན་བོད་ཤན་སྦྱར།༽
  author: ''
  volumes:
    01d50930002248e09fb0c16c8c8de34b:
      image_group_id: I2PD19047
      title: Volume 1 of gzhon nu drug gi rtogs brjod/ (dbyin bod shan sbyar/)
      volume_number: 1
      total_pages: 262
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
